version: '3.8'

services:
  # VIT SmartBot Application
  vit-smartbot:
    build: .
    container_name: vit-smartbot-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=vit_smartbot
      - NEXTAUTH_SECRET=vit-smartbot-production-secret
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - vit-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: vit-smartbot-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vitbot
      - MONGO_INITDB_ROOT_PASSWORD=vitbot123
      - MONGO_INITDB_DATABASE=vit_smartbot
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - vit-network
    restart: unless-stopped

  # MongoDB Admin Interface (Optional)
  mongo-express:
    image: mongo-express:latest
    container_name: vit-smartbot-admin
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=vitbot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=vitbot123
      - ME_CONFIG_MONGODB_URL=mongodb://vitbot:vitbot123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - vit-network
    restart: unless-stopped

networks:
  vit-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local